/**
 * Rank tiers, borrowed from MMO item quality. Surplus army power promotes the
 * capped ring of units up this ladder instead of adding bodies that would wreck
 * the formation's footprint.
 *
 * **The ladder has no last row.** `squadDps` reaches power only through these
 * rows, so wherever a ladder STOPS, every army-size bonus above it becomes a
 * measured no-op and the difficulty model's reference player starts picking
 * between options it cannot tell apart. That bug shipped once at 608 power
 * (red, the last authored row) and was "fixed" by appending six prestige ranks
 * - which moved it to 38,912 rather than removing it. A finite ladder always
 * reintroduces it somewhere, so the ladder is now GENERATED: threshold doubles
 * per row forever, damage and fire rate continue their geometric climb, and the
 * twelve authored rows below are one CYCLE of the palette rather than the whole
 * ladder. Row 12 wears Grey again, row 20 wears Gold again.
 *
 * The cycle is deliberately not marked. Nobody is watching for the loop itself;
 * what has to be legible is the change from one rung to the NEXT, and adjacent
 * rungs contrast whether or not the pass number is shown. Cycle-2 Gold looks
 * like cycle-1 Gold on purpose.
 */
export interface Tier {
  readonly name: string;
  readonly shirt: number;
  readonly trim: number;
  /** Power-per-unit required to reach this tier. */
  readonly threshold: number;
  readonly damage: number;
  readonly fireRate: number;
}

/**
 * One cycle of the palette, with the stats the authored region keeps exactly.
 * Rows past the last one here are generated by `tierRow`; nothing else should
 * index this table by rank.
 */
export const TIERS: readonly Tier[] = [
  { name: 'Grey',      shirt: 0x9aa3b5, trim: 0x6f7787, threshold: 1,    damage: 1,    fireRate: 1    },
  { name: 'Green',     shirt: 0x4ad07a, trim: 0x2c8a4e, threshold: 2,    damage: 1.8,  fireRate: 1.08 },
  { name: 'Blue',      shirt: 0x4aa8ff, trim: 0x2b6cb0, threshold: 4,    damage: 3.2,  fireRate: 1.16 },
  { name: 'Purple',    shirt: 0xa96bff, trim: 0x6f3fb5, threshold: 8,    damage: 5.8,  fireRate: 1.25 },
  { name: 'Orange',    shirt: 0xff9838, trim: 0xc2661a, threshold: 16,   damage: 10.5, fireRate: 1.35 },
  { name: 'Red',       shirt: 0xff4757, trim: 0xb22230, threshold: 32,   damage: 19,   fireRate: 1.5  },
  // --- prestige ---------------------------------------------------------
  { name: 'Bronze',    shirt: 0xc87f3a, trim: 0x8a4f1c, threshold: 64,   damage: 34,   fireRate: 1.62 },
  { name: 'Silver',    shirt: 0xd7dde8, trim: 0x8d97a8, threshold: 128,  damage: 61,   fireRate: 1.75 },
  { name: 'Gold',      shirt: 0xffd24a, trim: 0xbf8f10, threshold: 256,  damage: 110,  fireRate: 1.89 },
  { name: 'Platinum',  shirt: 0x9fe8ff, trim: 0x4d93ad, threshold: 512,  damage: 198,  fireRate: 2.04 },
  { name: 'Diamond',   shirt: 0x7af0d8, trim: 0x2f9c8a, threshold: 1024, damage: 356, fireRate: 2.2 },
  { name: 'Prismatic', shirt: 0xff8ff0, trim: 0xa93fa0, threshold: 2048, damage: 640,  fireRate: 2.38 },
];

/** Rows in one cycle of the palette. */
export const CYCLE = TIERS.length;

const LAST = TIERS[CYCLE - 1];

/**
 * Per-row growth past the authored region, EXTRACTED from the authored table
 * rather than invented: the geometric mean step across all eleven authored
 * steps (damage x1.799, fire rate x1.082 per doubling of power). The curve
 * through the authored rows is untouched, and the generated rows continue it
 * at the slope it already had.
 */
export const DAMAGE_STEP = Math.pow(LAST.damage / TIERS[0].damage, 1 / (CYCLE - 1));
export const RATE_STEP = Math.pow(LAST.fireRate / TIERS[0].fireRate, 1 / (CYCLE - 1));

/** Power-per-unit at the bottom of row `n`. */
export function tierThreshold(n: number): number {
  return Math.pow(2, n);
}

/**
 * Row `n` of the unbounded ladder. Authored rows come back verbatim; rows past
 * them wear `TIERS[n % CYCLE]`'s shirt and continue the stats geometrically.
 */
export function tierRow(n: number): Tier {
  if (n < CYCLE) return TIERS[n];
  const palette = TIERS[n % CYCLE];
  const past = n - (CYCLE - 1);
  return {
    name: palette.name,
    shirt: palette.shirt,
    trim: palette.trim,
    threshold: tierThreshold(n),
    damage: LAST.damage * Math.pow(DAMAGE_STEP, past),
    fireRate: LAST.fireRate * Math.pow(RATE_STEP, past),
  };
}

/**
 * Highest row whose threshold is met by this power-per-unit: `floor(log2)`,
 * with the float result checked against the exact thresholds either side so a
 * power that is exactly a power of two lands on its own row rather than one
 * below it.
 */
export function tierFor(powerPerUnit: number): number {
  if (!(powerPerUnit >= 2)) return 0;
  let n = Math.floor(Math.log2(powerPerUnit));
  if (tierThreshold(n + 1) <= powerPerUnit) n++;
  else if (tierThreshold(n) > powerPerUnit) n--;
  return n;
}

/**
 * Damage and fire rate for a unit holding this much power, interpolated
 * geometrically BETWEEN tier rows rather than stepped at them.
 *
 * Thresholds double, but bonus magnitudes are drawn from [1.05, 1.50] - so on a
 * stepped ladder a `x1.2 ARMY` would cross a threshold only occasionally and be
 * worth exactly nothing the rest of the time. A bonus that usually changes
 * nothing is the noise the design explicitly cuts, so power reaches damage
 * continuously and the tier row survives only as the visible rank.
 */
export function unitStats(powerPerUnit: number): { damage: number; fireRate: number } {
  const i = tierFor(powerPerUnit);
  const lo = tierRow(i);
  if (powerPerUnit <= lo.threshold) {
    return { damage: lo.damage, fireRate: lo.fireRate };
  }
  const hi = tierRow(i + 1);
  const f = Math.log(powerPerUnit / lo.threshold) / Math.log(hi.threshold / lo.threshold);
  return {
    damage: lo.damage * Math.pow(hi.damage / lo.damage, f),
    fireRate: lo.fireRate * Math.pow(hi.fireRate / lo.fireRate, f),
  };
}

/**
 * Bullet colour by DENSITY - how many real shots one drawn bullet stands for.
 *
 * Two collapses stack on the stream and this encodes their PRODUCT. The
 * simulation bundles the shots a build wants past `WEAPON.maxSimShotsPerSecond`
 * into fewer, heavier bullets (K real shots per spawned bullet), and the
 * renderer then draws a bounded subset of those (M spawned bullets per drawn
 * one). A drawn bullet therefore stands for K x M real shots, and that is the
 * number the tint is read from. Encoding M alone - what this did before the
 * simulation collapse existed - would read wrong past the sim ceiling, where
 * every drawn bullet is already several shots before the renderer thins it.
 *
 * This deliberately reuses the shirt ladder above rather than inventing a
 * second scale. It is already the game's vocabulary for "this thing stands for
 * more than it looks like" - a red unit is a unit carrying 32 power, not one
 * body - so a red bullet reads as heavy fire without the player learning
 * anything new. Thresholds double, which is the right shape: fire rate
 * compounds multiplicatively, so a linear scale would sit at the top for most
 * of a run. Like the shirts, it cycles rather than saturating.
 *
 * Tier 0 is the cream a bullet has always been, because at density under 2 a
 * drawn bullet IS a real bullet and nothing is being collapsed. The ladder
 * starts exactly where the lie starts.
 */
export const BULLET_BASE = 0xfff3b0;

export function bulletTint(density: number): number {
  const n = tierFor(density);
  return n === 0 ? BULLET_BASE : tierRow(n).shirt;
}
